version: "2.4"

services:
  postgresql:
    container_name: servicorodoviaria-postgresql
    extends:
      file: containers/postgresql.yml
      service: postgresql
  minio:
    container_name: servicorodoviaria-minio
    extends:
      file: containers/minio.yml
      service: minio
  elasticsearch:
    container_name: servicorodoviaria-elasticsearch
    extends:
      service: elasticsearch
      file: containers/elasticsearch.yml
