version: "2.4"

services:
  servicorodoviaria-postgresql:
    container_name: servicorodoviaria-postgresql
    extends:
      file: containers/postgresql.yml
      service: servicorodoviaria-postgresql
  servicorodoviaria-minio:
    container_name: servicorodoviaria-minio
    extends:
      file: containers/minio.yml
      service: servicorodoviaria-minio
