version: '2.4'

services:
  servicorodoviaria-minio:
    image: quay.io/minio/minio:RELEASE.2022-01-27T03-53-02Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
    command: server /data
